# Generated by Django 6.0 on 2025-12-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
